//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USER_PASSWORDS
    {
        public int ID { get; set; }
        public string SITE_NAME { get; set; }
        public string SITE_PASSWORD { get; set; }
        public int USER_ID { get; set; }
        public System.DateTime DATE_CREATED { get; set; }
        public System.DateTime DATE_MODIFIED { get; set; }
        public bool IS_DELETED { get; set; }
    
        public virtual TBL_LOGIN TBL_LOGIN { get; set; }
    }
}
